### ISSUE TITLE
emote script

### ISSUE THREAD

**Issue by rwhat** [blockba5her/FiveM-Emotes#1]
I am using the emote script...but when i do /emote smoke (or any other emote name) it broadcasts it to entire server through the chat...anyway to fix this easily>?

**Comment by DevBlocky** [comment]
What do you mean? What does the message say when broadcasted?

EDIT: Nevermind I know what you are talking about, fixing it ASAP.

**Comment by DevBlocky** [comment]
Alright, everything should be fixed and dandy! Thanks for the report. Just download the newest version and it is bound to work.

**Comment by rwhat** [comment]
Thanks man! I love the script...I do have one question..anyway to make it
just work with a /smoke instead of /emote smoke?
