### ISSUE TITLE
Failed to start client.lua

### ISSUE THREAD

**Issue by rhys19** [blockba5her/FiveM-Emotes#3]
I have an issue everytime i restart the script it says this in console & ingame:

https://gyazo.com/8267d162c77834772b6cbdb6325a0a64

ingame: 
![image](https://user-images.githubusercontent.com/30848481/35773181-479e5fd0-0910-11e8-9619-a04f71657ccb.png)

**Comment by DevBlocky** [comment]
It seems like you changed the file names a little bit. Make sure that you didn't accidentally swap the names of the files when changing them.

**Comment by DevBlocky** [comment]
i'm closing because it's inactive
